### ISSUE TITLE
https://hub.docker.com/r/studioetrange/bindfs does not exist

### ISSUE THREAD

**Issue by veselov** [StudioEtrange/docker-volume-bindfs#1]
This repository (https://hub.docker.com/r/studioetrange/bindfs) seems to have been removed/privatized.

**Comment by HeikoBoettger** [comment]
@StudioEtrange First of all, I really like to use this plugin since it looks like there has been done a lot of good improvements.

Since there wasn't any response on this issue and it's a small thing to do, please let us know whether there is a need to fork it.

If you have trouble with dockerhub, you might try whether the GitHub Docker Registry works better for you (see https://docs.github.com/en/packages/working-with-a-github-packages-registry/working-with-the-container-registry)

**Comment by StudioEtrange** [comment]
Sorry @HeikoBoettger 
Yes i plan to publish this plugin on GitHub Docker Registry :)
I will do it in a week :)

**Comment by StudioEtrange** [comment]
@HeikoBoettger @veselov 
You should use this plugin now with
docker plugin install ghcr.io/studioetrange/bindfs:2.1
or
docker plugin install ghcr.io/studioetrange/bindfs:latest

Tell me if it's ok

**Comment by mexmirror** [comment]
Hey @StudioEtrange. The image is not available yet. When trying to install it fails with an unauthorized error.

```
Error response from daemon: Head "https://ghcr.io/v2/studioetrange/bindfs/manifests/2.1": unauthorized
```

Would be great if this was available 😃

**Comment by StudioEtrange** [comment]
who know how to set my package as "public" ?

**Comment by StudioEtrange** [comment]
@mexmirror i do not find the option to make it visible :/ It looks like overcomplicated to find it !

**Comment by StudioEtrange** [comment]
@mexmirror I finally found the "make public" option on the package !
It should be fixed now !

Try
`docker plugin install ghcr.io/studioetrange/bindfs:latest`

**Comment by veselov** [comment]
Yeah, pulls just fine now.

**Comment by mexmirror** [comment]
It does work now 😃  Awesome, thank you!

**Comment by HeikoBoettger** [comment]
Thanks

**Comment by tknerr** [comment]
@StudioEtrange thanks for publishing `studioetrange/bindfs:2.3` for both arm64 and amd64 now! 🎉👍😃

**Comment by tknerr** [comment]
Side note: for a moment I thought that `studioetrange/bindfs:2.3` would be a multi-arch plugin image, but now reading I understand it defaults to the amd64 image... 👍

Just curious / wondering: do you know if it would be even possible to build plugins as multi-arch images?

**Comment by StudioEtrange** [comment]
I have tried to build a multiarch docker plugin, but it seems not possible.

So there is now 2.3 (default amd64) and 2.3-amd64 for amd64 arch and 2.3-arm64 for arm64 arch

**Comment by tknerr** [comment]
FYI - this is what made me think it was published as a multi-arch plugin:
https://github.com/StudioEtrange/docker-volume-bindfs/pull/2#issuecomment-2104392186

However, it was the presence of the `qemu-user-static` package which made it work when run under a foreign architecture...
